# We set the version of the file
version: '3.1'
# This part is explained below the file
services:
  web:
    build: .
    command: /bin/sh -c "rm -f /home/ubuntu/SocialFreak/tmp/pids/server.pid && bundle exec rake db:create db:migrate && rails server puma -p 80"
    volumes:
      - $PWD:/SocialFreak
    ports:
      - "80:80"
    links:
      - "db:database"
    env_file:
      - .env
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
  worker:
    build: .
    command: /bin/sh -c "bundle exec bin/delayed_job -n 1 --log-dir=/home/ubuntu/SocialFreak/shared/log/delayed_job.log --pool='notifications-poller:1' --pool='broadcast,default,elasticsearch,firebase:2' restart && bundle exec shoryuken --logfile '/home/ubuntu/SocialFreak/shared/log/shoryuken.log' --config '/home/ubuntu/SocialFreak/config/shoryuken_staging.yml' -R"
    links:
      - "db:database"
    volumes:
      - $PWD:/SocialFreak
    env_file:
      - .env